### ISSUE TITLE
Feature: Ability to configure length of git revision key

### ISSUE THREAD

**Issue by Bockit** [ember-cli-deploy/ember-cli-deploy-revision-data#22]
It would be nice if we could set the length, or even just a toggle for the whole thing.

**Comment by jrowlingson** [comment]
Ah, yes, I like this suggestion. I should be able to get to it tomorrow.

**Comment by Bockit** [comment]
That would be great, thanks

**Comment by viniciussbs** [comment]
I'm trying to use a Rollbar addon to track errors and an Ember CLI Deploy plugging to send the source maps to Rollbar. The problem is that the Rollbar addon uses version + the first **7** chars of the commit hash and this plugging uses version + the first **8** chars of the commit hash.

Reading the README, I saw that this plugging actually uses 2 different hash lengths according to the generator. Git [Commit generator uses 7 chars](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data#revisionkey-2) and [Version Commit generator uses 8 chars](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data#revisionkey-3).

So, turning this configurable is a feature, but should we treat this inconsistency a bug - and, in this case, open a new issue for it?
